apiVersion: v1
kind: Pod
metadata:
  name: cs-pod
  labels:
    app: cs-pod
spec:
  containers:
  - name: cs-pod-container
    image: johnlenin/microservices:cs
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cs-service
spec:
  selector:
    app: cs-pod
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: go-pod
  labels:
    app: go-pod
spec:
  containers:
  - name: go-pod-container
    image: johnlenin/microservices:go
    ports:
    - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go-pod
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Pod
metadata:
  name: ts-pod
  labels:
    app: ts-pod
spec:
  containers:
  - name: ts-pod-container
    image: johnlenin/microservices:ts-v3
    ports:
    - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: ts-pod
  ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Pod
metadata:
  name: py-pod
  labels:
    app: py-pod
spec:
  containers:
  - name: py-pod-container
    image: johnlenin/microservices:py-v2
    ports:
    - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: py-pod
  ports:
    - port: 8083
      targetPort: 8083
---