apiVersion: v1
kind: Pod
metadata:
  name: cs-pod
  labels:
    app: cs-pod
spec:
  containers:
  - name: cs-pod-container
    image: johnlenin/microservices:cs
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cs-service
spec:
  selector:
    app: cs-pod
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: go-pod
  labels:
    app: go-pod
spec:
  containers:
  - name: go-pod-container
    image: johnlenin/microservices:go
    ports:
    - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go-pod
  ports:
    - port: 8081
      targetPort: 8081
---
