apiVersion: v1
kind: Pod
metadata:
  name: go-pod
spec:
  containers:
  - name: go-pod-container
    image: johnlenin/microservices:latest
    ports:
    - name: http
      containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  type: NodePort
  selector:
      app: go-pod
  ports:
  - name: http
    port: 8081
    targetPort: http
    nodePort: 30000
---
apiVersion: v1
kind: Pod
metadata:
  name: go-pod2
spec:
  containers:
  - name: go-pod-container
    image: johnlenin/microservices:latest
    ports:
    - name: http
      containerPort: 8081
