FROM node:21
WORKDIR /usr/src/app
COPY package*.json ./
RUN apt-get update && apt-get install -y \
       libvips-dev \
       && rm -rf /var/lib/apt/lists/*
RUN npm install
COPY . .
RUN npm run
CMD ["node", "app.ts"]
